server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: backend
          uri: lb://BACKEND
          predicates:
            - Path=/client/**,/trip/**,/passenger/count/**
        - id: backendfront
          uri: lb://BACKENDFRONT
          predicates:
            - Path=/generateTicket/**
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true