version: '3.4'

x-common-variables: &common-variables
  MYSQL_HOST: mysqldb
  EUREKA_HOST: eureka-server

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./init/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
    networks:
      - application

  backend:
    image: rbernabeulopez/backend
    ports:
      - '8080:8080'
    networks:
      - application
    depends_on:
      - eureka-server
      - mysqldb
    environment: *common-variables

  backend-front:
    image: rbernabeulopez/backend-front
    ports:
      - '8081:8081'
    networks:
      - application
    depends_on:
      - eureka-server
      - mysqldb
    environment: *common-variables

  api-gateway:
    image: rbernabeulopez/api-gateway
    ports:
      - '8082:8082'
    networks:
      - application
    depends_on:
      - backend
      - backend-front
    environment: *common-variables

  eureka-server:
    image: rbernabeulopez/eureka-naming-server
    ports:
      - '8761:8761'
    networks:
      - application

networks:
  application:
    driver: bridge